/**
 * Copyright (c) 2019, Example Company
 *
 * THIS WORK CONTAINS PROPRIETARY INFORMATION WHICH IS THE PROPERTY OF
 * Example Company AND IS SUBJECT TO THE TERMS OF NON-DISCLOSURE AGREEMENT
 * BETWEEN Example Company AND THE COMPANY USING THIS FILE.
 *
 */
